"""Build AGMA records_live.jsonl from extracted browser data."""
import json
import os
from datetime import datetime, timezone

# All 433 records extracted from https://agma.org/membership/member-list
# Format: (company_name, website, member_type, domain)
RECORDS = [
    # === CORPORATE (386) ===
    ("ABA-PGT, Inc.", "http://www.abapgt.com/", "corporate", "abapgt.com"),
    ("Ace World Companies", "http://www.aceworldcompanies.com/", "corporate", "aceworldcompanies.com"),
    ("The Adams Company", "https://www.theadamscompany.com/", "corporate", "theadamscompany.com"),
    ("Advanced Jiffy Machine Products", "http://www.advancedjiffymachine.com/", "corporate", "advancedjiffymachine.com"),
    ("Aero Gear, Inc.", "http://www.aerogear.com/", "corporate", "aerogear.com"),
    ("AeroMotion by Textron Aviation", "https://aeromotion.txtav.com/", "corporate", "aeromotion.txtav.com"),
    ("AF Services Aceros Forjados Y Cia Ltda", "http://www.acerosforjados.com/", "corporate", "acerosforjados.com"),
    ("Affolter Group SA", "http://www.affoltergroup.ch/", "corporate", "affoltergroup.ch"),
    ("Afton Chemical Corporation", "http://www.aftonchemical.com/", "corporate", "aftonchemical.com"),
    ("A.H. Gears Ltd", "https://ahgears.com/", "corporate", "ahgears.com"),
    ("Akron Gear & Engineering, Inc.", "https://www.akrongear.com/", "corporate", "akrongear.com"),
    ("ALD Thermal Treatment", "https://www.heat-treatment-services.com/locations/ald-thermal-treatment-usa/", "corporate", "heat-treatment-services.com"),
    ("ALD Tratamientos Termicos S.A. De C.V.", "http://www.ald-vt.com/", "corporate", "ald-vt.com"),
    ("ALD Vacuum Technologies North America, Inc.", "http://www.ald-vt.com/", "corporate", "ald-vt.com"),
    ("Allison Transmission, Inc.", "http://www.allisontransmission.com/", "corporate", "allisontransmission.com"),
    ("Amarillo Gear Company LLC", "http://www.amarillogear.com/", "corporate", "amarillogear.com"),
    ("American Axle & Manufacturing", "https://www.aam.com/", "corporate", "aam.com"),
    ("American Gear Inc.", "http://www.americangearinc.com/", "corporate", "americangearinc.com"),
    ("American Machine & Gear Inc.", "http://www.amgearpdx.com/", "corporate", "amgearpdx.com"),
    ("American Metal Treating Company", "http://www.americanmetaltreating.com/", "corporate", "americanmetaltreating.com"),
    ("American Precision Gear", "http://www.amgear.com/index.html", "corporate", "amgear.com"),
    ("American Rheinmetall", "http://www.rheinmetall-arv-us.com/", "corporate", "rheinmetall-arv-us.com"),
    ("Ameridrives Couplings, a Regal Rexnord Brand", "https://www.ameridrives.com/", "corporate", "ameridrives.com"),
    ("Amper", "http://amper.xyz/", "corporate", "amper.xyz"),
    ("Apex Gear Service, Inc.", "https://apexgearservice.com/", "corporate", "apexgearservice.com"),
    ("Applied Process Inc. DBA Aalberts Surface Technologies", "http://www.appliedprocess.com/", "corporate", "appliedprocess.com"),
    ("Artec Machine Systems", "http://www.artec-machine.com/", "corporate", "artec-machine.com"),
    ("Ash Gear & Supply Corporation", "http://www.ashgear.com/", "corporate", "ashgear.com"),
    ("ASI Drives", "http://www.asidrives.com/", "corporate", "asidrives.com"),
    ("Atlanta Gear Works Inc.", "http://www.atlantagear.com/", "corporate", "atlantagear.com"),
    ("Atlantic Bearing Services", "http://www.atlantic-bearing.com/", "corporate", "atlantic-bearing.com"),
    ("Atlantic Sintered, Inc.", "https://atlanticsintered.com/", "corporate", "atlanticsintered.com"),
    ("Atlas Copco Comptec LLC", "http://www.atlascopco.com/", "corporate", "atlascopco.com"),
    ("Atlas Gear Company", "https://www.atlasgear.com/", "corporate", "atlasgear.com"),
    ("Atlas Global", "https://www.atlasglobalcompany.com/", "corporate", "atlasglobalcompany.com"),
    ("Avers Machine and Gear dba Innovative Rack & Gear", "http://www.gearacks.com/", "corporate", "gearacks.com"),
    ("B&D Industrial", "http://www.bdindustrial.com/", "corporate", "bdindustrial.com"),
    ("B&R Machine & Gear Corporation", "http://www.brgear.com/", "corporate", "brgear.com"),
    ("Bendon Gear & Machine, Inc.", "http://www.bendongear.com/", "corporate", "bendongear.com"),
    ("Bevel Gears India", "http://www.bevelgearsindia.com/", "corporate", "bevelgearsindia.com"),
    ("Blaser Swisslube, Inc.", "http://www.blaser.com/", "corporate", "blaser.com"),
    ("Bodine Electric Company", "http://www.bodine-electric.com/", "corporate", "bodine-electric.com"),
    ("The Boeing Company", "http://www.boeing.com/", "corporate", "boeing.com"),
    ("Bonfiglioli USA", "http://www.bonfiglioli.com/", "corporate", "bonfiglioli.com"),
    ("Boston Gear, a Regal Rexnord Brand", "https://www.bostongear.com/", "corporate", "bostongear.com"),
    ("Bourn & Koch Inc.", "http://www.bourn-koch.com/", "corporate", "bourn-koch.com"),
    ("Brad Foote Gear Works, Inc.", "http://www.bradfoote.com/", "corporate", "bradfoote.com"),
    ("Brelie Gear Company, Inc.", "http://www.breliegear.com/", "corporate", "breliegear.com"),
    ("Broadwind Towers and Heavy Fabrications Broadwind Energy", "http://www.broadwindenergy.com/", "corporate", "broadwindenergy.com"),
    ("Brother International Corporation", "http://www.brothergearmotors.com/", "corporate", "brothergearmotors.com"),
    ("B.S.L. Machine Limited", "https://www.bslmachine.com/", "corporate", "bslmachine.com"),
    ("Buffalo Gear", "https://www.buffalogear.com/", "corporate", "buffalogear.com"),
    ("Camco Engineering", "http://www.camcoeng.com.au/", "corporate", "camcoeng.com.au"),
    ("Castrol USA", "http://www.castrol.com/us", "corporate", "castrol.com"),
    ("Caterpillar Foundation", "http://www.caterpillar.com/", "corporate", "caterpillar.com"),
    ("Caterpillar Global Mining HMS GmbH", "http://www.caterpillar.com/", "corporate", "caterpillar.com"),
    ("Caterpillar Global Mining LLC", "http://www.mining.cat.com/", "corporate", "mining.cat.com"),
    ("Caterpillar Inc.", "http://www.caterpillar.com/", "corporate", "caterpillar.com"),
    ("Caterpillar Industrias Mexico CV", "http://www.caterpillar.com/", "corporate", "caterpillar.com"),
    ("C-B Gear & Machine, Inc.", "http://www.cbgear.com/", "corporate", "cbgear.com"),
    ("CGI, Inc.", "http://www.cgimotion.com/", "corporate", "cgimotion.com"),
    ("Chalmers & Kubeck, Inc.", "http://www.candk.com/", "corporate", "candk.com"),
    ("Cincinnati Steel Treating", "https://steeltreating.com/", "corporate", "steeltreating.com"),
    ("Circle Gear and Machine Company", "http://www.circlegear.com/", "corporate", "circlegear.com"),
    ("Cleveland Gear Company", "http://www.clevelandgear.com/", "corporate", "clevelandgear.com"),
    ("Columbia Gear Corporation", "http://www.columbiagear.com/", "corporate", "columbiagear.com"),
    ("Combat Vehicles Research & Development Establishment", "http://www.drdo.gov.in/labs-and-establishments/combat-vehicles-research-development-estt-cvrde", "corporate", "drdo.gov.in"),
    ("Comer Industries, Inc.", "http://www.comerindustries.com/", "corporate", "comerindustries.com"),
    ("Commercial Gear & Sprocket Co., Inc.", "http://www.commercialgear.com/", "corporate", "commercialgear.com"),
    ("Cone Drive, by Timken", "https://conedrive.com/", "corporate", "conedrive.com"),
    ("Conifer", "https://conifer.io/", "corporate", "conifer.io"),
    ("Cotta, LLC", "http://www.cotta.com/", "corporate", "cotta.com"),
    ("Croix Gear", "http://www.croixgear.com/", "corporate", "croixgear.com"),
    ("Crown Equipment Corporation", "http://www.crown.com/", "corporate", "crown.com"),
    ("Curtis Machine Company", "http://www.curtismachine.com/", "corporate", "curtismachine.com"),
    ("Curtiss Weight Corporation - Actuation Division - Aerospace", "https://www.cw-actuation.com/", "corporate", "cw-actuation.com"),
    ("Custom Machine & Mechanical Services Ltd.", "https://www.custommachine.ca/", "corporate", "custommachine.ca"),
    ("Dana Motion Systems Deutschland GmbH", "https://www.piv-extruderdrives.com/", "corporate", "piv-extruderdrives.com"),
    ("David Brown Santasalo Ltd.", "https://dbsantasalo.com/", "corporate", "dbsantasalo.com"),
    ("David Brown Santasalo South Africa (Pty) Limited", "https://dbsantasalo.com/", "corporate", "dbsantasalo.com"),
    ("David Brown Santasalo USA Inc.", "http://www.santasalo.com/", "corporate", "santasalo.com"),
    ("DBS Manufacturing, Inc.", "http://www.dbsmfg.com/", "corporate", "dbsmfg.com"),
    ("Deca Industries", "http://www.decaindustries.com/", "corporate", "decaindustries.com"),
    ("Delom Services, Inc", "http://www.wajax.com/", "corporate", "wajax.com"),
    ("Delta Dynamics Inc.", "http://www.deltadynamics.com/", "corporate", "deltadynamics.com"),
    ("De'Ran Gear, Inc.", "http://www.derangear.com/", "corporate", "derangear.com"),
    ("Di Bacco Y CIA SA", "https://www.dibacco.com.ar/", "corporate", "dibacco.com.ar"),
    ("Dodge Industrial, Inc.", "https://dodgeindustrial.com/", "corporate", "dodgeindustrial.com"),
    ("Dodson Group", "https://dodsongroup.com/", "corporate", "dodsongroup.com"),
    ("Doppler Gear Company", "http://www.dopplergear.com/", "corporate", "dopplergear.com"),
    ("DVS Technology America, Inc.", "http://www.dvs-gruppe.de/", "corporate", "dvs-gruppe.de"),
    ("Eaton Corporation", "http://www.eaton.com/", "corporate", "eaton.com"),
    ("Eaton Corporation - Vehicle Group", "http://www.eaton.com/", "corporate", "eaton.com"),
    ("Eaton Electrical Sensing and Controls", "http://www.eaton.com/", "corporate", "eaton.com"),
    ("Eaton Kearney Manufacturing Plant", "http://www.eaton.com/", "corporate", "eaton.com"),
    ("Eaton Ltda - Div. Transmissoes", "http://www.eaton.com.br/EatonBR/ProductsSolutions/Vehicle/Contate-nos/index.htm", "corporate", "eaton.com.br"),
    ("Eaton Marshall Technical Center", "http://www.eaton.com/", "corporate", "eaton.com"),
    ("ECM USA, Inc.", "http://www.ecm-usa.com/", "corporate", "ecm-usa.com"),
    ("Edgerton Gear, Inc.", "http://www.edgertongear.com/", "corporate", "edgertongear.com"),
    ("EMAG, L.L.C.", "http://www.emag.com/", "corporate", "emag.com"),
    ("Engrenage Kustom Gear Inc.", "http://www.kustomgear.net/fr/", "corporate", "kustomgear.net"),
    ("Engrenages Sherbrooke Inc.", "http://sherbrookegearworks.com/", "corporate", "sherbrookegearworks.com"),
    ("Engrenages Specialises Inc.", "http://www.engramex.com.mx/", "corporate", "engramex.com.mx"),
    ("Envirodyne Systems Inc.", "http://www.envirodynesystems.com/", "corporate", "envirodynesystems.com"),
    ("Essential Power Transmission Pvt Ltd.", "http://www.esenpro.com/", "corporate", "esenpro.com"),
    ("The Estell Group", "http://www.theestellgroup.com/", "corporate", "theestellgroup.com"),
    ("Euro Gear", "http://www.eurogearinc.com/", "corporate", "eurogearinc.com"),
    ("Evolvent Design, LLC.", "http://evolventdesign.com/", "corporate", "evolventdesign.com"),
    ("Excel Gear, Inc.", "https://horsburgh-scott.com/", "corporate", "horsburgh-scott.com"),
    ("ExxonMobil", "http://www.exxonmobil.com/", "corporate", "exxonmobil.com"),
    ("ExxonMobil Research and Engineering", "http://www.exxonmobil.com/", "corporate", "exxonmobil.com"),
    ("Fairlane Gear Inc.", "http://www.fairlane-gear.com/", "corporate", "fairlane-gear.com"),
    ("Fathom5", "http://www.fathom5.co/", "corporate", "fathom5.co"),
    ("FCMD North America", "http://www.ferrycapitain.fr/", "corporate", "ferrycapitain.fr"),
    ("Federal Gear and Machine", "http://www.federalgear.com/", "corporate", "federalgear.com"),
    ("Felsomat USA, Inc.", "https://www.felsomat.com/", "corporate", "felsomat.com"),
    ("Ferry-Capitain", "http://www.ferrycapitain.fr/", "corporate", "ferrycapitain.fr"),
    ("Finkl Steel", "http://www.finkl.com/", "corporate", "finkl.com"),
    ("First Gear Engineering & Technology", "http://www.first-gear.com/", "corporate", "first-gear.com"),
    ("Flender Corp.", "https://www.flender.com/products/gearUnits", "corporate", "flender.com"),
    ("FLENDER GmbH", "http://www.flender.com/", "corporate", "flender.com"),
    ("FLSmidth, Inc.", "http://www.flsmidth.com/", "corporate", "flsmidth.com"),
    ("Forest City Gear Company", "http://www.forestcitygear.com/", "corporate", "forestcitygear.com"),
    ("Formosa Heavy Industries Corp.", "https://www.fhi.com.tw/official/Index.aspx", "corporate", "fhi.com.tw"),
    ("Franklin Machine & Gear Corporation", "http://www.franklingear.com/", "corporate", "franklingear.com"),
    ("Freudenberg-Nok Sealing Technologies", "https://www.fst.com/", "corporate", "fst.com"),
    ("Fuller Technologies", "https://www.fuller-technologies.com/", "corporate", "fuller-technologies.com"),
    ("Gallmar Industries, LLC", "http://www.fvht.com/", "corporate", "fvht.com"),
    ("GAM Enterprises", "http://www.gamweb.com/", "corporate", "gamweb.com"),
    ("Gamesa Gearbox SA", "https://www.gamesagearbox.com/", "corporate", "gamesagearbox.com"),
    ("GE Vernova", "https://www.gevernova.com/", "corporate", "gevernova.com"),
    ("Gear Manufacturing, Inc.", "http://www.gearmfg.com/", "corporate", "gearmfg.com"),
    ("Gear Motions, Inc.", "http://www.gearmotions.com/", "corporate", "gearmotions.com"),
    ("Gear Motions - Buffalo Operations", "https://gearmotions.com/locations/buffalo-division/", "corporate", "gearmotions.com"),
    ("GearTec, Inc.", "http://www.geartec.com/", "corporate", "geartec.com"),
    ("General Atomics Aeronautical Systems", "http://www.ga-asi.com/", "corporate", "ga-asi.com"),
    ("General Electric Company GE Aerospace", "https://www.geaerospace.com/", "corporate", "geaerospace.com"),
    ("General Motors LLC", "https://www.gm.com/", "corporate", "gm.com"),
    ("General Motors LLC - Engine Lab & PBC", "http://www.gm.com/", "corporate", "gm.com"),
    ("German Machine Tools of America", "http://www.gmtamerica.com/", "corporate", "gmtamerica.com"),
    ("Gibbs Machinery Company", "http://www.gibbsmachinery.com/", "corporate", "gibbsmachinery.com"),
    ("Gleason Corporation", "http://www.gleason.com/", "corporate", "gleason.com"),
    ("Gleason Cutting Tools Corp.", "http://www.gleason.com/", "corporate", "gleason.com"),
    ("Gleason Family Foundation", "http://www.gleason.com/", "corporate", "gleason.com"),
    ("Gleason Metrology Systems Corporation", "http://www.gleason.com/", "corporate", "gleason.com"),
    ("Gleason-Pfauter Maschinenfabrik GmbH", "https://www.gleason.com/de/operations/gleason-pfauter-maschinenfabrik-gmbh-ludwigsburg-germany", "corporate", "gleason.com"),
    ("Gleason Switzerland AG", "http://www.gleason.com/", "corporate", "gleason.com"),
    ("The Gleason Works", "http://www.gleason.com/", "corporate", "gleason.com"),
    ("Global Gear & Machining LLC", "http://www.globalgearllc.com/", "corporate", "globalgearllc.com"),
    ("Great Lakes Industry, Inc", "http://www.greatlakesind.com/", "corporate", "greatlakesind.com"),
    ("Great Taiwan Gear Ltd.", "http://www.taiwangear.com/", "corporate", "taiwangear.com"),
    ("Griffin Gear, Inc.", "http://www.griffingear.com/", "corporate", "griffingear.com"),
    ("Groschopp Inc.", "http://www.groschopp.com/", "corporate", "groschopp.com"),
    ("GWJ Technology GmbH", "http://www.gwj.de/", "corporate", "gwj.de"),
    ("Hainbuch America Corporation Workholding Technology", "http://www.hainbuchamerica.com/", "corporate", "hainbuchamerica.com"),
    ("Haley Marine Gears, Inc.", "http://www.haleyinc.com/", "corporate", "haleyinc.com"),
    ("Hansen Industrial Transmissions, NV", "http://www.hansenindustrialgearboxes.com/", "corporate", "hansenindustrialgearboxes.com"),
    ("Helios Gear Products", "https://heliosgearproducts.com/", "corporate", "heliosgearproducts.com"),
    ("HM Manufacturing", "http://www.hmmanufacturing.com/", "corporate", "hmmanufacturing.com"),
    ("HMC Gears", "http://www.hmcgears.com/", "corporate", "hmcgears.com"),
    ("Hofmann Engineering Pty. Ltd.", "http://www.hofmann.net.au/", "corporate", "hofmann.net.au"),
    ("Hoffman Filter", "https://www.hoffmannfilter.com/", "corporate", "hoffmannfilter.com"),
    ("Honeywell Aerospace", "http://www.honeywell.com/", "corporate", "honeywell.com"),
    ("Horsburgh & Scott Company", "http://www.horsburgh-scott.com/", "corporate", "horsburgh-scott.com"),
    ("Hyosung Heavy Industries Corporation", "http://www.hyosungheavyindustries.com/en/main.do", "corporate", "hyosungheavyindustries.com"),
    ("Hy-Tech Engineered Solutions", "http://www.hy-techinc.com/", "corporate", "hy-techinc.com"),
    ("I.D.C. Industries Inc.", "http://www.idcind.com/", "corporate", "idcind.com"),
    ("I-MAK Reduktor", "http://www.imakreduktor.com/", "corporate", "imakreduktor.com"),
    ("IMS Companies", "http://www.imsmfg.com/", "corporate", "imsmfg.com"),
    ("Index Technologies, Inc.", "https://indextechnologiesinc.com/", "corporate", "indextechnologiesinc.com"),
    ("Ingenium Aerospace", "https://www.ingeniumaerospace.com/", "corporate", "ingeniumaerospace.com"),
    ("Ingersoll Rand", "http://www.irco.com/", "corporate", "irco.com"),
    ("INNIO Waukesha Gas Engines, Inc.", "http://www.innio.com/", "corporate", "innio.com"),
    ("Integrated Machinery Solutions, LLC", "http://www.team-ims.com/", "corporate", "team-ims.com"),
    ("International Precision Machining, Inc", "http://www.ipminc.com/", "corporate", "ipminc.com"),
    ("IPTS, Inc.", "http://www.iptsinc.com/", "corporate", "iptsinc.com"),
    ("Ishibashi Manufacturing Co., Ltd", "http://www.ishibashi-mfg.com/", "corporate", "ishibashi-mfg.com"),
    ("ITAMCO", "http://www.itamco.com/", "corporate", "itamco.com"),
    ("Jet Avion Corporation", "http://www.heico.com/", "corporate", "heico.com"),
    ("JIE USA, Inc.", "https://jie-drives.com/", "corporate", "jie-drives.com"),
    ("John Deere - Technology Center India", "http://www.deere.com/", "corporate", "deere.com"),
    ("John Deere Coffeyville Works", "http://www.deere.com/", "corporate", "deere.com"),
    ("John Deere Product Engineering Center", "https://www.deere.com/en/our-company/john-deere-careers/interview-resources/waterloo-works/", "corporate", "deere.com"),
    ("Johnson Gear", "http://www.johnsongear.com/", "corporate", "johnsongear.com"),
    ("KAPP NILES GmbH & Co. KG", "http://www.kapp-niles.com/", "corporate", "kapp-niles.com"),
    ("KAPP Technologies", "http://www.kapp-niles.com/", "corporate", "kapp-niles.com"),
    ("Kearfott Corp.", "https://www.kearfott.com/", "corporate", "kearfott.com"),
    ("Ker-Train Research, Inc.", "https://kertrain.com/", "corporate", "kertrain.com"),
    ("Kinetics Drive Solutions Inc.", "http://www.kdsolutionsgroup.com/", "corporate", "kdsolutionsgroup.com"),
    ("KISSsoft AG", "http://www.kisssoft.com/", "corporate", "kisssoft.com"),
    ("KISSsoft, USA, LLC", "http://www.kisssoft.com/", "corporate", "kisssoft.com"),
    ("Klingelnberg Ag", "http://www.klingelnberg.com/", "corporate", "klingelnberg.com"),
    ("Klingelnberg America, Inc.", "http://www.klingelnberg.com/", "corporate", "klingelnberg.com"),
    ("Klingelnberg GmbH", "http://www.klingelnberg.com/", "corporate", "klingelnberg.com"),
    ("Koellmann Gear Corporation", "http://www.koellmann.com/", "corporate", "koellmann.com"),
    ("Krebs & Riedel Schleifscheibenfabrik GmbH & Co. KG.", "https://www.krebs-riedel.com/", "corporate", "krebs-riedel.com"),
    ("KTR Corporation", "https://www.ktr.com/", "corporate", "ktr.com"),
    ("Kumera Oy", "http://www.kumera.com/", "corporate", "kumera.com"),
    ("Kupral S.p.a.", "http://www.kupral.com/", "corporate", "kupral.com"),
    ("L&H Industrial", "http://www.lnh.net/", "corporate", "lnh.net"),
    ("Lawler Gear", "https://lawlergear.com/", "corporate", "lawlergear.com"),
    ("Liebherr Gear and Automation Technologies, Inc.", "http://www.liebherr.com/", "corporate", "liebherr.com"),
    ("Liebherr USA, Co.", "http://www.liebherr.com/", "corporate", "liebherr.com"),
    ("Liebherr Verzahntechnik GmbH", "https://www.liebherr.com/en/usa/about-liebherr/liebherr-worldwide/germany/kempten/liebherr-verzahntechnik-gmbh.html", "corporate", "liebherr.com"),
    ("Lightnin", "https://www.spxflow.com/lightnin/", "corporate", "spxflow.com"),
    ("Linamar Corporation", "https://www.linamar.com/", "corporate", "linamar.com"),
    ("Linn Gear Company", "http://www.linngear.com/", "corporate", "linngear.com"),
    ("Lovejoy, by Timken", "https://www.lovejoy-inc.com/", "corporate", "lovejoy-inc.com"),
    ("The Lubrizol Corporation", "http://www.lubrizol.com/", "corporate", "lubrizol.com"),
    ("Lufkin Gears LLC", "http://www.lufkingears.com/", "corporate", "lufkingears.com"),
    ("Lufkin Industries, LLC, a BHGE Company", "http://www.lufkin.com/", "corporate", "lufkin.com"),
    ("Luftex Gears", "http://www.luftexgears1.com/", "corporate", "luftexgears1.com"),
    ("MAAG Gear S.p.A", "https://www.maaggear.com/", "corporate", "maaggear.com"),
    ("MAAG Gear Sp. z.o.o.", "https://www.maaggear.com/", "corporate", "maaggear.com"),
    ("Machine Tool Builders Inc.", "http://www.machinetoolbuilders.com/", "corporate", "machinetoolbuilders.com"),
    ("Machinery Maintenance Rebuilders, Inc.", "https://mmrservice.com/", "corporate", "mmrservice.com"),
    ("Machinists Inc.", "http://www.machinistsinc.com/", "corporate", "machinistsinc.com"),
    ("Magtorq Private Limited", "https://www.magtorq.org/", "corporate", "magtorq.org"),
    ("Malloy Electric", "https://www.malloyelectric.com/", "corporate", "malloyelectric.com"),
    ("Marmon Holdings, Inc.", "https://www.marmon.com/", "corporate", "marmon.com"),
    ("Martin Sprocket & Gear, Inc.", "http://www.martinsprocket.com/", "corporate", "martinsprocket.com"),
    ("Master Power Transmission, Inc.", "http://www.master-pt.com/", "corporate", "master-pt.com"),
    ("McInnis Rolled Rings", "http://www.mcinnesrolledrings.com/", "corporate", "mcinnesrolledrings.com"),
    ("Mercury Marine", "http://www.mercurymarine.com/", "corporate", "mercurymarine.com"),
    ("Meritor", "https://www.meritor.com/", "corporate", "meritor.com"),
    ("Metallus", "https://metallus.com/", "corporate", "metallus.com"),
    ("Metso Corporation", "http://www.metso.com/", "corporate", "metso.com"),
    ("Mi TechCan Services", "https://www.motionindustries.com/", "corporate", "motionindustries.com"),
    ("Milwaukee Electric Tool Corporation", "http://www.milwaukeetool.com/", "corporate", "milwaukeetool.com"),
    ("Mitutoyo", "https://www.mitutoyo.com/", "corporate", "mitutoyo.com"),
    ("Motor & Gear Engineering, Inc.", "http://www.motorgearengineer.com/", "corporate", "motorgearengineer.com"),
    ("Nachi America Inc.", "http://www.nachiamerica.com/", "corporate", "nachiamerica.com"),
    ("NAMCO Machine & Gear Works Ltd.", "http://www.namco.ca/", "corporate", "namco.ca"),
    ("National Laboratory of the Rockies (NLR)", "https://www.nrel.gov/", "corporate", "nrel.gov"),
    ("Naval Surface Warfare Center - Philadelphia Division Code 426", "http://www.navsea.navy.mil/home/warfare-centers/nswc-philadelphia/", "corporate", "navsea.navy.mil"),
    ("Nidec Machine Tool America", "https://www.mitsubishitoday.com/", "corporate", "mitsubishitoday.com"),
    ("Nippon Gear Company, Ltd.", "http://www.nippon-gear.jp/english/", "corporate", "nippon-gear.jp"),
    ("Nixon Gear, Inc.", "http://www.gearmotions.com/", "corporate", "gearmotions.com"),
    ("Nord Gear Corporation", "http://www.nord.com/", "corporate", "nord.com"),
    ("Nordex, Incorporated", "http://www.nordex.com/", "corporate", "nordex.com"),
    ("Northrop Grumman Corporation", "http://www.northropgrumman.com/", "corporate", "northropgrumman.com"),
    ("Novus Gear LTD", "https://www.novusgear.co.za/", "corporate", "novusgear.co.za"),
    ("Nuttall Gear, a Regal Rexnord Brand", "http://www.nuttallgear.com/", "corporate", "nuttallgear.com"),
    ("Omni Gear & Machine Corp.", "https://omnigear.us/", "corporate", "omnigear.us"),
    ("Ontario Drive & Gear Ltd.", "http://www.odg.com/", "corporate", "odg.com"),
    ("Orbix Corporation DBA Petol Gearench", "http://www.gearench.com/", "corporate", "gearench.com"),
    ("Oregon Induction + Thermal", "http://www.oregoninductioncorp.com/", "corporate", "oregoninductioncorp.com"),
    ("Oshkosh Corporation", "http://www.oshkoshcorporation.com/", "corporate", "oshkoshcorporation.com"),
    ("Ovako North America, Inc.", "http://www.ovako.com/", "corporate", "ovako.com"),
    ("Overly Hautz Company", "https://overlyhautz.com/", "corporate", "overlyhautz.com"),
    ("Overton Chicago Gear Corporation", "http://www.oc-gear.com/", "corporate", "oc-gear.com"),
    ("Ovivo, USA, LLC", "http://www.ovivowater.com/", "corporate", "ovivowater.com"),
    ("Pacific Rim Engineered Products", "http://www.prepglobal.com/", "corporate", "prepglobal.com"),
    ("PAI Industries, Inc.", "http://www.paiindustries.com/", "corporate", "paiindustries.com"),
    ("Peerless-Winsmith, Inc.", "http://www.winsmith.com/", "corporate", "winsmith.com"),
    ("Penn Machine Company LLC", "http://www.pennmach.com/", "corporate", "pennmach.com"),
    ("Penta Gear Metrology LLC", "http://pentagear.com/en/", "corporate", "pentagear.com"),
    ("Perfection Gear", "https://www.perfectiongear.com/", "corporate", "perfectiongear.com"),
    ("Performance Gear Systems, Inc.", "http://www.performance-gear.com/", "corporate", "performance-gear.com"),
    ("Perry Technology Corporation", "http://www.perrygear.com/", "corporate", "perrygear.com"),
    ("Petron Corporation", "http://www.petroncorp.com/", "corporate", "petroncorp.com"),
    ("Philadelphia Gear, Power Systems by Timken", "http://www.philagear.com/", "corporate", "philagear.com"),
    ("PIC Design, Division of Roller Bearing Company of America, Inc.", "http://www.pic-design.com/", "corporate", "pic-design.com"),
    ("Piselli Enterprises Inc.", "https://www.pisellient.com/", "corporate", "pisellient.com"),
    ("Portescap, a Regal Rexnord Brand", "http://www.portescap.com/", "corporate", "portescap.com"),
    ("Potesta and Company, LLC", "https://www.slewpro.com/", "corporate", "slewpro.com"),
    ("Power Engineering & Manufacturing, Ltd.", "http://www.pemltd.com/", "corporate", "pemltd.com"),
    ("Power Transmission Group", "https://ptggear.com/", "corporate", "ptggear.com"),
    ("Pragati Transmission Pvt. Ltd.", "http://www.pragatgears.com/", "corporate", "pragatgears.com"),
    ("Pratt & Whitney", "https://www.prattwhitney.com/", "corporate", "prattwhitney.com"),
    ("Precipart Corporation", "http://www.precipart.com/", "corporate", "precipart.com"),
    ("Precision Arrow Gear", "https://arrowgear.com/index.html", "corporate", "arrowgear.com"),
    ("Precision Gage Company", "http://www.precisiongageco.com/", "corporate", "precisiongageco.com"),
    ("Premier Gear & Machine Works, Inc.", "https://www.premier-gear.com/", "corporate", "premier-gear.com"),
    ("Profiroll Technologies USA, Inc.", "https://www.profiroll.com/index.html", "corporate", "profiroll.com"),
    ("R & I Instrument & Gear Co (Aust) Pty Ltd", "https://www.rigear.com.au/", "corporate", "rigear.com.au"),
    ("Radiac Abrasives, A TYROLIT Company", "http://www.radiac.com/", "corporate", "radiac.com"),
    ("Randolph Gear Inc.", "http://www.randolphgear.com/", "corporate", "randolphgear.com"),
    ("Rapid Gear", "http://www.rapidgear.com/", "corporate", "rapidgear.com"),
    ("Regal Rexnord", "http://www.regalpts.com/", "corporate", "regalpts.com"),
    ("Reishauer AG", "http://www.reishauer.com/", "corporate", "reishauer.com"),
    ("Reliance Gear Corporation", "http://www.reliancegear.com/", "corporate", "reliancegear.com"),
    ("REM Surface Engineering", "http://www.remchem.com/", "corporate", "remchem.com"),
    ("RENK AG Rheine", "http://www.renk.biz/", "corporate", "renk.biz"),
    ("RENK America", "https://www.renk.com/de", "corporate", "renk.com"),
    ("RENK GmbH", "http://www.renk.eu/", "corporate", "renk.eu"),
    ("RENK-MAAG GmbH", "http://www.renk-maag.ch/", "corporate", "renk-maag.ch"),
    ("Renold, Inc.", "http://www.renold.com/", "corporate", "renold.com"),
    ("Rheo AI", "https://rheo.ai/", "corporate", "rheo.ai"),
    ("Richmond Area Common Equity, LLC DBA Progressive Engineering Co.", "http://pecgears.com/", "corporate", "pecgears.com"),
    ("Richardson Manufacturing Company", "http://www.rmc-bigcnc.com/", "corporate", "rmc-bigcnc.com"),
    ("Riley Gear", "https://www.rileygear.com/", "corporate", "rileygear.com"),
    ("Riverside Spline & Gear, Inc.", "http://www.splineandgear.com/", "corporate", "splineandgear.com"),
    ("Rj Link International, Inc", "http://www.rjlink.com/", "corporate", "rjlink.com"),
    ("Robust Gear and Industries Inc.", "http://www.robustgear.com/", "corporate", "robustgear.com"),
    ("Rochester Gear, Inc.", "http://www.rochestergear.com/", "corporate", "rochestergear.com"),
    ("Rolls-Royce Corp.", "http://www.rolls-royce.com/", "corporate", "rolls-royce.com"),
    ("Ronson Gears Pty., Ltd.", "http://www.ronsongears.com/", "corporate", "ronsongears.com"),
    ("Russell, Holbrook & Henderson", "http://www.tru-volute.com/", "corporate", "tru-volute.com"),
    ("RWE Clean Energy", "https://www.rwe.com/en/the-group/rwe-clean-energy/", "corporate", "rwe.com"),
    ("S.L. Munson & Company", "http://www.slmunson.com/", "corporate", "slmunson.com"),
    ("San Engineering & Locomotive Co. Ltd", "http://www.san-engineering.com/", "corporate", "san-engineering.com"),
    ("Schafer Gear Works Rockford, LLC", "http://www.schafergear.com/", "corporate", "schafergear.com"),
    ("Schafer Industries", "http://www.schaferindustries.com/", "corporate", "schaferindustries.com"),
    ("Schelde Gears, a Company of the RENK Group", "http://www.renk.eu/", "corporate", "renk.eu"),
    ("Schulz Electric, Power Systems By Timken", "https://www.schulzgroupusa.com/schulzelectric/index.htm", "corporate", "schulzgroupusa.com"),
    ("Scot Forge Company", "http://www.scotforge.com/", "corporate", "scotforge.com"),
    ("SECO/WARWICK CORPORATION", "http://www.secovacusa.com/", "corporate", "secovacusa.com"),
    ("SEW-Eurodrive GmbH & Co.", "http://www.sew-eurodrive.de/", "corporate", "sew-eurodrive.de"),
    ("SEW-Eurodrive, Inc.", "http://www.seweurodrive.com/", "corporate", "seweurodrive.com"),
    ("Shanghai Zhenhua Heavy Industries Co., Ltd", "http://www.zpmc.com/", "corporate", "zpmc.com"),
    ("Shell Global Solutions (US) Inc.", "http://www.shellglobalsolutions.com/", "corporate", "shellglobalsolutions.com"),
    ("Shell Lubricants", "https://www.shell.com/business-customers/lubricants-for-business.html", "corporate", "shell.com"),
    ("Sikorsky Aircraft A Lockheed Martin Company", "http://www.sikorsky.com/", "corporate", "sikorsky.com"),
    ("Sinto America, Inc.", "https://sintoamerica.com/", "corporate", "sintoamerica.com"),
    ("SIPCO-I-MAK", "http://www.sipco-mls.com/", "corporate", "sipco-mls.com"),
    ("SM Cyclo De Mexico, SA De CV", "http://www.sumitomodrive.com/", "corporate", "sumitomodrive.com"),
    ("SM Cyclo of Canada, Ltd.", "http://www.sumitomodrive.com/", "corporate", "sumitomodrive.com"),
    ("Smith Services, Power Systems by Timken", "http://www.smithservices.com/", "corporate", "smithservices.com"),
    ("SMT", "http://www.smartmt.com/", "corporate", "smartmt.com"),
    ("Solar Turbines Incorporated", "http://www.solarturbines.com/", "corporate", "solarturbines.com"),
    ("Southern Gear & Machine, Inc.", "http://www.southerngear.net/", "corporate", "southerngear.net"),
    ("Specialty Steel Treating", "http://www.specialtysteeltreating.com/", "corporate", "specialtysteeltreating.com"),
    ("Spencer Pettus Machine Company", "http://www.spgear.com/", "corporate", "spgear.com"),
    ("SPXFLOW Philadelphia Mixing Solutions", "http://www.philamixers.com/", "corporate", "philamixers.com"),
    ("Standard Machine, Power Systems by Timken", "http://standardmachine.ca/", "corporate", "standardmachine.ca"),
    ("Stanley Black & Decker", "https://www.stanleyblackanddecker.com/", "corporate", "stanleyblackanddecker.com"),
    ("Star Cutter Company", "http://www.starcutter.com/", "corporate", "starcutter.com"),
    ("Star SU Tawas Tool Co / Star Cutter", "http://www.star-su.com/", "corporate", "star-su.com"),
    ("Star SU, LLC", "http://www.star-su.com/", "corporate", "star-su.com"),
    ("Sterling Electric Inc.", "http://www.sterlingelectric.com/", "corporate", "sterlingelectric.com"),
    ("Steward Machine Co., Inc.", "http://www.stewardmachine.com/", "corporate", "stewardmachine.com"),
    ("Stock Drive Products", "https://sdp-si.com/", "corporate", "sdp-si.com"),
    ("/Sterling Instrument (SDP/SI)", "http://sdp-si.com/", "corporate", "sdp-si.com"),
    ("Stoneridge Control Devices", "http://stoneridge.com/", "corporate", "stoneridge.com"),
    ("Sumitomo Drive Technologies", "http://smcyclo.com/", "corporate", "smcyclo.com"),
    ("Sumitomo Heavy Industries Gearbox Co., Ltd.", "http://www.shigearbox.com/", "corporate", "shigearbox.com"),
    ("Sumitomo Heavy Industries, Ltd.", "http://www.shi.co.jp/", "corporate", "shi.co.jp"),
    ("SUNGEAR, Inc.", "http://www.sungearinc.com/", "corporate", "sungearinc.com"),
    ("Supreme Gear Company", "http://www.supremegear.com/", "corporate", "supremegear.com"),
    ("Temp Makine Imalat Teknolojileri Anonim Sirketi", "https://tempmakine.com/en/", "corporate", "tempmakine.com"),
    ("ThermTech", "http://www.thermtech.net/", "corporate", "thermtech.net"),
    ("THORs ELearning Solutions, LLC", "http://www.thors.com/", "corporate", "thors.com"),
    ("thyssenkrupp Polysius", "http://www.a-cequipment.com/", "corporate", "a-cequipment.com"),
    ("Tien Yi Gear Works Co., Ltd.", "http://www.tienyigear.com.tw/", "corporate", "tienyigear.com.tw"),
    ("Timken Company", "http://www.timken.com/", "corporate", "timken.com"),
    ("Tokyo Technical Instruments Inc.", "http://www.tti-geartec.jp/", "corporate", "tti-geartec.jp"),
    ("Top Gear Transmission PVT. Ltd.", "https://topgeartransmission.com/events-news/", "corporate", "topgeartransmission.com"),
    ("Triumph Gear Systems", "http://www.triumphgroup.com/", "corporate", "triumphgroup.com"),
    ("Triumph Gear Systems-Macomb, Inc.", "http://www.triumphgroup.com/", "corporate", "triumphgroup.com"),
    ("Triumph Group Inc.", "http://www.triumphgroup.com/", "corporate", "triumphgroup.com"),
    ("Triveni Engineering and Industries Ltd.", "http://www.trivenigroup.com/", "corporate", "trivenigroup.com"),
    ("Tsubakimoto Chain Co.", "https://tsubakimoto.com/", "corporate", "tsubakimoto.com"),
    ("Tsung Yin Machine Work Corp.", "http://www.tsungyin.com.tw/", "corporate", "tsungyin.com.tw"),
    ("Twin Disc, Incorporated", "http://www.twindisc.com/", "corporate", "twindisc.com"),
    ("Ueda Heavy Gear Works Ltd.", "http://www.ueda-tekkosho.co.jp/", "corporate", "ueda-tekkosho.co.jp"),
    ("Unigear Industries, Inc.", "http://www.unigear.com/", "corporate", "unigear.com"),
    ("United Gear & Assembly, Inc.", "http://www.ugaco.com/", "corporate", "ugaco.com"),
    ("United Gear & Machine Company, Inc.", "http://www.unitedgearct.com/", "corporate", "unitedgearct.com"),
    ("United Gear & Machine Works, Limited", "http://www.unitedgear.com/", "corporate", "unitedgear.com"),
    ("United Protective Technologies, Inc.", "http://www.upt-usa.com/", "corporate", "upt-usa.com"),
    ("Usinatech", "http://usinatech.com/", "corporate", "usinatech.com"),
    ("Vector Companies", "https://www.vectorcompanies.com/", "corporate", "vectorcompanies.com"),
    ("Vestas Technology R&D", "http://www.vestas.com/", "corporate", "vestas.com"),
    ("Vestas Wind Systems A/S", "http://www.vestas.com/", "corporate", "vestas.com"),
    ("Vigor Precision Ltd.", "http://www.vigorprecision.com.hk/", "corporate", "vigorprecision.com.hk"),
    ("Volvo Powertrain North America", "http://www.volvo.com/", "corporate", "volvo.com"),
    ("Walker Process Equipment", "http://www.walker-process.com/", "corporate", "walker-process.com"),
    ("Walterscheid Inc.", "https://www.walterscheid.com/en/home/", "corporate", "walterscheid.com"),
    ("Waterous Company", "https://www.waterousco.com/", "corporate", "waterousco.com"),
    ("WD Bearings America LLC", "https://wdbearings.com/", "corporate", "wdbearings.com"),
    ("WEG Cestari Monte Alto and WEG Cestari", "http://www.wegcestari.com.br/", "corporate", "wegcestari.com.br"),
    ("WEG Electric Corp", "https://www.weg.net/institutional/BR/pt/", "corporate", "weg.net"),
    ("WEG Equipamentos Eletricos S.A.", "https://www.weg.net/institutional/BR/pt/", "corporate", "weg.net"),
    ("WEG Gear Systems GmbH", "https://www.wattdrive.com/de/", "corporate", "wattdrive.com"),
    ("WEG Turbinas e Solar Ltda", "https://www.weg.net/institutional/BR/pt/", "corporate", "weg.net"),
    ("Weiler Abrasives", "https://www.weilerabrasives.com/", "corporate", "weilerabrasives.com"),
    ("Wenzel America, Ltd.", "http://www.wenzelamerica.com/", "corporate", "wenzelamerica.com"),
    ("Western Precision Aero LLC", "http://www.westernprecisionaero.com/", "corporate", "westernprecisionaero.com"),
    ("WFL Millturn Technologies", "https://www.wfl.at/en", "corporate", "wfl.at"),
    ("Wikov Gear Canada", "https://www.wikov.com/en/contacts/wikov-wessex-inc", "corporate", "wikov.com"),
    ("Winergy AG", "http://www.winergy-group.com/", "corporate", "winergy-group.com"),
    ("Winergy Drive Systems Corporation", "http://www.winergy-usa.com/", "corporate", "winergy-usa.com"),
    ("Wipro Givon USA", "https://wiproaerospace.com/", "corporate", "wiproaerospace.com"),
    ("Xtek, Inc.", "http://www.xtek.com/", "corporate", "xtek.com"),
    ("Zenar Corporation", "http://www.zenarcrane.com/", "corporate", "zenarcrane.com"),
    # === CONSULTANT (15) ===
    ("A Boughey Pty Ltd", "http://www.boughey.com/", "consultant", "boughey.com"),
    ("AKGears, LLC", "http://www.akgears.com/", "consultant", "akgears.com"),
    ("Bay Machine Design", "http://www.baymachinedesign.com/", "consultant", "baymachinedesign.com"),
    ("Drive Systems Technology, Inc.", "http://www.gear-doc.com/", "consultant", "gear-doc.com"),
    ("Estudio Pina", "http://www.estudiopina.com.ar/", "consultant", "estudiopina.com.ar"),
    ("MetConsult LLC", "http://www.metconsultllc.com/", "consultant", "metconsultllc.com"),
    ("MESYS AG", "http://www.mesys.ch/", "consultant", "mesys.ch"),
    ("Milburn Engineering, Inc.", "http://www.milburnengineering.com/", "consultant", "milburnengineering.com"),
    ("Powertrain Engineers, Inc.", "http://www.powertrainengineers.com/", "consultant", "powertrainengineers.com"),
    ("Schoolcraft PowerTrain Inc.", "http://www.schoolcraftpowertrain.com/", "consultant", "schoolcraftpowertrain.com"),
    ("Sintered Metal Consulting, LLC", "https://sinteredmetalconsulting.com/", "consultant", "sinteredmetalconsulting.com"),
    ("Studio Tecnico Turci", "http://www.turci.biz/", "consultant", "turci.biz"),
    ("Walter Consulting LLC", "mailto:walterconsulting1@outlook.com", "consultant", ""),
    ("Web Gear Services Ltd.", "https://www.webgearservices.com/", "consultant", "webgearservices.com"),
    ("Zackory Camberbeek, Canadian Gear Company", "http://canadiangearcompany.com/", "consultant", "canadiangearcompany.com"),
    # === ACADEMIC (32) ===
    ("Beaver Racing - Oregon State University", "https://beaverracing.org/", "academic", "beaverracing.org"),
    ("British Columbia Institute of Technology", "https://www.bcit.ca/", "academic", "bcit.ca"),
    ("Ecole de technologie superieure", "https://www.etsmtl.ca/", "academic", "etsmtl.ca"),
    ("Florida International University", "https://www.fiu.edu/", "academic", "fiu.edu"),
    ("Gear Research Center (FZG), Technical University of Munich (TUM)", "http://www.fzg.mw.tum.de/", "academic", "fzg.mw.tum.de"),
    ("Gear Research Institute", "http://www.arl.psu.edu/", "academic", "arl.psu.edu"),
    ("Imperial College of Science, Technology & Medicine", "http://www3.imperial.ac.uk/", "academic", "www3.imperial.ac.uk"),
    ("Indian Institute of Technology Guwahati", "http://www.iitg.ernet.in/", "academic", "iitg.ernet.in"),
    ("Instituto Tecnologico de Aeronautica", "http://www.ita.br/", "academic", "ita.br"),
    ("Longato Riccardo SRLS", "https://www.longatosrls.it/wp/", "academic", "longatosrls.it"),
    ("Mississippi State University - Mechanical Engineering Department", "http://www.me.msstate.edu/", "academic", "me.msstate.edu"),
    ("Mondragon Goi Eskola Politeknikoa JMA S. Coop", "http://www.mondragon.edu/en/phs", "academic", "mondragon.edu"),
    ("National Technical University of Athens", "http://www.ntua.gr/", "academic", "ntua.gr"),
    ("Ohio State University, Dept. of Mechanical Eng.", "http://www.gearlab.org/", "academic", "gearlab.org"),
    ("Penn State Berks", "http://www.bk.psu.edu/", "academic", "bk.psu.edu"),
    ("Politecnico Di Milano", "http://www.polimi.it/", "academic", "polimi.it"),
    ("Polytechnic University of Cartagena", "http://www.upct.es/", "academic", "upct.es"),
    ("Rochester Institute of Technology", "https://www.rit.edu/grc/", "academic", "rit.edu"),
    ("The University of Sheffield", "https://www.sheffield.ac.uk/", "academic", "sheffield.ac.uk"),
    ("TU Dresden - Institut fuer Maschinenelemente und Maschinenkonstruktion", "https://tu-dresden.de/ing/maschinenwesen/imm/me/", "academic", "tu-dresden.de"),
    ("UNED, ETSI Industriales", "http://www.uned.es/", "academic", "uned.es"),
    ("Universidade Do Porto Facultade De Engenharia", "http://www.fe.up.pt/", "academic", "fe.up.pt"),
    ("University of Alberta", "https://www.ualberta.ca/engineering/mechanical-engineering/index.html", "academic", "ualberta.ca"),
    ("University of Huddersfield", "http://www.hud.ac.uk/", "academic", "hud.ac.uk"),
    ("University of Massachusetts Lowell", "http://www.uml.edu/", "academic", "uml.edu"),
    ("University of Newcastle-Upon-Tyne, Design Unit", "http://www.ncl.ac.uk/gears", "academic", "ncl.ac.uk"),
    ("University of Puerto Rico-Mayaguez", "http://www.uprm.edu/", "academic", "uprm.edu"),
    ("University of Tennessee at Chattanooga", "https://www.utc.edu/", "academic", "utc.edu"),
    ("UWM-Mechanical Engineering Department", "https://uwm.edu/engineering/academics-2/departments/mechanical-engineering/", "academic", "uwm.edu"),
    ("Vienna University of Technology", "http://www.ikl.tuwien.ac.at/machine_design/EN", "academic", "ikl.tuwien.ac.at"),
    ("Werkzeugmaschinen Labor", "http://www.wzl.rwth-aachen.de/", "academic", "wzl.rwth-aachen.de"),
    ("Zhengzhou University of Aeronautics", "https://zua.edu.cn/", "academic", "zua.edu.cn"),
]


def main():
    now = datetime.now(timezone.utc).isoformat()
    output_dir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "data", "raw", "AGMA"
    )
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "records_live.jsonl")

    lines = []
    counts = {}
    domains = set()

    for name, website, member_type, domain in RECORDS:
        record = {
            "company_name": name,
            "association": "AGMA",
            "member_type": member_type,
            "source_url": "https://agma.org/membership/member-list",
            "extracted_at": now,
            "country": "United States",
            "website": website,
            "domain": domain,
        }
        lines.append(json.dumps(record, ensure_ascii=False))
        counts[member_type] = counts.get(member_type, 0) + 1
        if domain:
            domains.add(domain)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Wrote {len(lines)} records to {output_path}")
    print(f"By member type: {counts}")
    print(f"Unique domains: {len(domains)}")
    print(f"\nFirst 3:")
    for line in lines[:3]:
        r = json.loads(line)
        print(f"  {r['company_name']} | {r['member_type']} | {r['domain']}")
    print(f"Last 3:")
    for line in lines[-3:]:
        r = json.loads(line)
        print(f"  {r['company_name']} | {r['member_type']} | {r['domain']}")


if __name__ == "__main__":
    main()
